### PR TITLE
installed mermaid.js

### LINKED ISSUE #294: Support mermaid.js
I am currently working on issue #291, #292, and #293 and would like to propose adding mermaid.js as a new library for docusaurus. Mermaid will enable us to generate graphics directly from markdown, which will eliminate the need for another tool to maintain and ensure that the graphs are part of the source control. 

I have already created a local branch configured with mermaid. If there are no objections, I will proceed to open a PR.

### PR DESCRIPTION
**Pull request by magdmartin**
fix #294

### CODE REVIEW

**Comment by magdmartin** [comment]
I am unsure how to address the Netlify build error. While building locally, I received the following messages. when I run `npm start` the local server works correctly. 

 Any assistance would be appreciated.

```
yarn build
yarn run v1.22.19
$ docusaurus build
[INFO] [en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 10.26s


✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

[WARNING] Docusaurus found broken anchors!

Please check the pages of your site in the list below, and make sure you don't reference any anchor that does not exist.
Note: it's possible to ignore broken anchors with the 'onBrokenAnchors' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /community:
   -> linking to /docs/technical-reference/contributing#contributing-to-the-documentation
- Broken anchor on source page path = /docs/manual/cellediting:
   -> linking to exploring#row-types-rows-vs-records (resolved as: /docs/manual/exploring#row-types-rows-vs-records)
   -> linking to #phonetic-clustering (resolved as: /docs/manual/cellediting#phonetic-clustering)
   -> linking to #fingerprinting (resolved as: /docs/manual/cellediting#fingerprinting)
   -> linking to #n-gram (resolved as: /docs/manual/cellediting#n-gram)
   -> linking to #metaphone3-fingerprinting (resolved as: /docs/manual/cellediting#metaphone3-fingerprinting)
   -> linking to #cologne-fingerprinting (resolved as: /docs/manual/cellediting#cologne-fingerprinting)
   -> linking to #daitch-mokotoff (resolved as: /docs/manual/cellediting#daitch-mokotoff)
   -> linking to #baider-morse (resolved as: /docs/manual/cellediting#baider-morse)
   -> linking to #levenshtein-distance (resolved as: /docs/manual/cellediting#levenshtein-distance)
   -> linking to #ppm (resolved as: /docs/manual/cellediting#ppm)
- Broken anchor on source page path = /docs/manual/columnediting:
   -> linking to cellediting#rows-vs-records (resolved as: /docs/manual/cellediting#rows-vs-records)
- Broken anchor on source page path = /docs/manual/exploring:
   -> linking to transforming#to-date (resolved as: /docs/manual/transforming#to-date)
   -> linking to transforming#split-multi-valued-cells (resolved as: /docs/manual/transforming#split-multi-valued-cells)
- Broken anchor on source page path = /docs/manual/exporting:
   -> linking to #sql-statement-exporter (resolved as: /docs/manual/exporting#sql-statement-exporter)
- Broken anchor on source page path = /docs/manual/facets:
   -> linking to running#project-grid-header (resolved as: /docs/manual/running#project-grid-header)
   -> linking to transforming#cluster-and-edit (resolved as: /docs/manual/transforming#cluster-and-edit)
   -> linking to #cell-data-types (resolved as: /docs/manual/facets#cell-data-types)
- Broken anchor on source page path = /docs/manual/grelfunctions:
   -> linking to #diffsd1-sd2-s-timeunit-optional (resolved as: /docs/manual/grelfunctions#diffsd1-sd2-s-timeunit-optional)
- Broken anchor on source page path = /docs/manual/installing:
   -> linking to running#records-mode (resolved as: /docs/manual/running#records-mode)
   -> linking to #install-or-upgrade-java (resolved as: /docs/manual/installing#install-or-upgrade-java)
- Broken anchor on source page path = /docs/manual/jythonclojure:
   -> linking to grelfunctions#jsoup-xml-and-html-parsing-functions (resolved as: /docs/manual/grelfunctions#jsoup-xml-and-html-parsing-functions)
   -> linking to #reconciliation (resolved as: /docs/manual/jythonclojure#reconciliation)
- Broken anchor on source page path = /docs/manual/reconciling:
   -> linking to expressions#GREL (resolved as: /docs/manual/expressions#GREL)
   -> linking to expressions#reconciliaton-variables (resolved as: /docs/manual/expressions#reconciliaton-variables)
- Broken anchor on source page path = /docs/manual/running:
   -> linking to installing#linux (resolved as: /docs/manual/installing#linux)
   -> linking to exploring#sort-and-view (resolved as: /docs/manual/exploring#sort-and-view)
- Broken anchor on source page path = /docs/manual/starting:
   -> linking to grelfunctions#crosscell-s-projectname-s-columnname (resolved as: /docs/manual/grelfunctions#crosscell-s-projectname-s-columnname)
   -> linking to grelfunctions#reinterprets-s-encoder (resolved as: /docs/manual/grelfunctions#reinterprets-s-encoder)
- Broken anchor on source page path = /docs/manual/transforming:
   -> linking to columnediting#rename-remove-and-move (resolved as: /docs/manual/columnediting#rename-remove-and-move)
   -> linking to columnediting#split-or-join (resolved as: /docs/manual/columnediting#split-or-join)
- Broken anchor on source page path = /docs/manual/wikibase/overview:
   -> linking to #edit-wikidata-schema (resolved as: /docs/manual/wikibase/overview#edit-wikidata-schema)
   -> linking to ./reconciling#add-columns-from-reconciled-values (resolved as: /docs/manual/wikibase/reconciling#add-columns-from-reconciled-values)
- Broken anchor on source page path = /docs/manual/wikibase/reconciling:
   -> linking to reconciling#reconciling-with-unique-identifiers (resolved as: /docs/manual/wikibase/reconciling#reconciling-with-unique-identifiers)
- Broken anchor on source page path = /docs/manual/wikibase/schema-alignment:
   -> linking to ./uploading#Merging-strategies-for-statements (resolved as: /docs/manual/wikibase/uploading#Merging-strategies-for-statements)
- Broken anchor on source page path = /docs/technical-reference/architecture-before-4:
   -> linking to #importingcontrollers (resolved as: /docs/technical-reference/architecture-before-4#importingcontrollers)

[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
Done in 15.15s.
```

**Comment by wetneb** [comment]
I have spent quite some time investigating and I still have zero clue what is going on here!
Let me attempt an update of the yarn.lock to see if it magically solves problems (wishful thinking).

**Comment by wetneb** [comment]
Well I don't know what happened to your `yarn.lock` you added initially but updating it with `yarn install` seems to have solved the problem.
Quick, let's merge while it's still green!

**Comment by magdmartin** [comment]
thank you

**Pull request merged**
