### PR TITLE
Upload Offline pdf docs

### PR DESCRIPTION
**Pull request by monstajoe2002**

### CODE REVIEW

**Comment by wetneb** [comment]
Apologies in the delay for reviewing this. I don't think uploading a static PDF in this repository is a good move as it will get outdated as docs are edited.

**Comment by ostephens** [comment]
Perhaps implementing a docusaurus plugin like https://github.com/jean-humann/docs-to-pdf might be an option?

**Comment by monstajoe2002** [comment]
I tried that, it's no different than the other plugin. Also, it didn't work on my machine.

**Comment by ostephens** [comment]
@wetneb having looked more closely now (sorry @monstajoe2002 ) I realise that the intent here is that the pdf is generated and updated by a GitHub workflow https://github.com/OpenRefine/openrefine.org/pull/304/commits/2d9bf1aa3705817fd0a3ccc43d83a837bcd168f1

If this works I don't think there should be concerns about it being outdated as long as it gets generated as the repo is updated?

**Comment by ostephens** [comment]
Sorry both - I've deleted my last comment as I think it was totally wrong

**Comment by ostephens** [comment]
@monstajoe2002 I agree with @wetneb uploading a static file is not a good solution here. I feel there must be a better solution - what were the issues you saw with docs-to-pdf and prince?

**Comment by thadguidry** [comment]
A much better way to handle this would be to NOT USE PDF, but instead bundle the website and maintain all the HTML content.

Folks would locally view the site just by unzipping the bundled site and then clicking on the `index` file and the routing is handled through hash routing and the site locally accessed with `file://index.html`.
We could bundle the site (or perhaps just the `/docs` folder)  at build time into a GitHub artifact release and on the site have a link in the footer or header that downloads that offline site zip file.
The implementation would use the new **Docusaurus offline browsing feature** now supported in version 3.4 (which I also have a PR for folks to review that fixes the broken anchors).

More detail on how to do this is here: https://docusaurus.io/blog/releases/3.4#hash-router---experimental

**Comment by ostephens** [comment]
@monstajoe2002 I'd really like to support achieving your goal here, but I wonder if you could:

* describe in more detail what your aim is (why are you adding the PDF - is it for a printable version? Or to have one that works offline?)
* describe the issues you encountered when trying to use the plugins to automatically generate the PDF

**Comment by magdmartin** [comment]
@ostephens I agree with your point. Let's keep the requirement in #275 
@monstajoe2002 I am closing this PR as we refine the requirement first.

**Pull request closed without merging**
